### ISSUE TITLE
[FEATURE] mono version

### ISSUE THREAD

**Issue by magnetophon** [jatinchowdhury18/AnalogTapeModel#118]
To reduce resource usage, a mono version would be very welcome.

**Comment by jatinchowdhury18** [comment]
Hmmm, maintaining a separate mono-only version of the plugin would be a lot of extra work... Is this something that a lot of people are interested in? (I wish there were a way to do polls in GitHub issues)

**Comment by magnetophon** [comment]
Nah, if it entails ongoing effort, forget about it.
I thought it was going to be a one time effort.

Your time is better spent elsewhere, I wasn't gong to use it that often anyway.
