### ISSUE TITLE
[BUG] Audio instability at extreme values of tone treble, bass, and frequency

### ISSUE THREAD

**Issue by tesselode** [jatinchowdhury18/AnalogTapeModel#120]
In the tone section, if treble is set to -1.0, bass is set to 1.0, and frequency is set to a value at around 2.9kHz or higher, the audio will pop and then become permanently silent.

If treble is set to 1.0 and bass is set to -1.0, the audio will become unstable and continuously output heavy distortion.

In both cases, the instability only happens if the input is not silent.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DAW: Renoise
 - Version: 2.7
 - 64 bit

[unstable patches.zip](https://github.com/jatinchowdhury18/AnalogTapeModel/files/5768367/unstable.patches.zip)

**Comment by jatinchowdhury18** [comment]
Hi @tesselode, thanks for reporting this, and for sharing the example patches! Unfortunately, I've been unable to re-create this issue with my normal setup (Windows 10, VST2 in Ableton 10). Would it be possible to also share an audio file that you've seen the issue occur with? Also, I'm wondering if you observe any differences with this issue when you change the Oversampling amount, or the Hysteresis Mode? I'm not super familiar with Renoise, so I'm also curious if there's anything particularly different in the way they handle audio levels... I'll try to do some research here.

Thanks,
Jatin

**Comment by tesselode** [comment]
Hi, sorry for the delay. I attached a Renoise project file that shows the instability as well as a rendered audio file. Changing the oversampling and hysteresis options didn't seem to change anything.

I was not able to reproduce this issue with FL Studio.

[chow tape model instability.zip](https://github.com/jatinchowdhury18/AnalogTapeModel/files/5791836/chow.tape.model.instability.zip)

**Comment by jatinchowdhury18** [comment]
Hmm, yeah seems like something specific to how Renoise does their gain staging. I'll see about getting a trial version of Renoise so I can debug more easily.

**Comment by jatinchowdhury18** [comment]
Okay, I've adjusted the way I'm doing internal gain staging, specifically when being hosted by Renoise. If you have a minute, could you let me know how [these builds](https://github.com/jatinchowdhury18/AnalogTapeModel/tree/renoise-unstable/Plugin/Bin/Win64) work for you?

**Comment by tesselode** [comment]
That build works perfectly, thanks!

**Comment by jatinchowdhury18** [comment]
Great! Just merged.
