### ISSUE TITLE
[BUG] GUI vanishes

### ISSUE THREAD

**Issue by zainsohail04** [jatinchowdhury18/AnalogTapeModel#131]
Firstly, I want to say that you did an amazing job with the plugin! It makes any track sound warmer and better sounding (especially the included presets are great). 

I am facing a problem with the plugin GUI disappearing after some time in my session.

This has happened a few times already, and I am not sure why it happens. All my other plugins function fine.

**Screenshot**
![image](https://user-images.githubusercontent.com/10053031/106345439-744e8080-62b0-11eb-9e23-db0dad72b3ab.png)

**Desktop**
 - OS: Windows
 - DAW: Cakewalk
 - Version: Latest
 - 64 bit

Hope you can shed some light.

**Comment by jatinchowdhury18** [comment]
Thanks for the bug report! Yeah, this is pretty strange... I haven't seen this bug in any of the DAWs that I've tested in so far. I'll see if I can get a demo version of Cakewalk, and see if I can re-create the bug from there.

Just to double check, this is with ChowTape version 2.7.0?

**Comment by zainsohail04** [comment]
> Thanks for the bug report! Yeah, this is pretty strange... I haven't seen this bug in any of the DAWs that I've tested in so far. I'll see if I can get a demo version of Cakewalk, and see if I can re-create the bug from there.

Cakewalk has become freeware from last 2 years or so, so it should be easy to get a copy.

> Just to double check, this is with ChowTape version 2.7.0?

Yes

**Comment by jatinchowdhury18** [comment]
Yes, I was able to download Cakewalk. Cool that they made it free! Unfortunately, I haven't been able to re-create the bug with the GUI showing up all white like that.

Have you noticed any particular sequence of actions that causes the GUI to behave this way? Also, which specific version of Cakewalk are you using? Maybe I can reach out to the developers and see if they have any idea.

Thanks,
Jatin

**Comment by zainsohail04** [comment]
> Yes, I was able to download Cakewalk. Cool that they made it free! Unfortunately, I haven't been able to re-create the bug with the GUI showing up all white like that.
> 
> Have you noticed any particular sequence of actions that causes the GUI to behave this way? Also, which specific version of Cakewalk are you using? Maybe I can reach out to the developers and see if they have any idea.
> 
> Thanks,
> Jatin

I think it only happened when I had a lot of plugins loaded into my session. I am using 2021.01 (Build 085, 64 bit). Thanks for all your help! I think the plugin still functions but changing the parameters is not possible till I restart cakewalk, after which the GUI comes back.

**Comment by TableAble** [comment]
Hey, similar problem here.
Black Screen gui on the plugin, though the presets pull-down has a list that I am able to choose from.
But then, the gui remains black. 
I'm on WIndows 10 64 bit, and Studio One 5 Professional.

Thanks for anyhelp!  I'd like to try the plugin !!
- Phil

**Comment by jatinchowdhury18** [comment]
Hi Phil, thanks for reporting this as well. Just to clarify, for you the GUI shows up as a black screen from the very first time you open the plugin?

I've used up all of my demo time for Studio One, so I may have to ask Presonus for some support with this.

Thanks,
Jatin

**Comment by jatinchowdhury18** [comment]
Thinking about this a little more... I'm wondering if it's a rendering issue with OpenGL. I'll try to get some test builds up later today that you both could try out.

**Comment by TableAble** [comment]
Thank you I really appreciate you doing that. If there’s anything I can do on this end, just let me know. I have Studio One 5 professional, as well as studio one 2.



________________________________

**Comment by jatinchowdhury18** [comment]
Hi all, I've made a new build of the plugin for Windows, not use OpenGL for renderring the UI. Definitely let me know if it works better with your setup! https://github.com/jatinchowdhury18/AnalogTapeModel/tree/gui-vanishing-fix/Plugin/Bin

**Comment by zainsohail04** [comment]
It says the archive is damaged so I can't extract it.

**Comment by jatinchowdhury18** [comment]
Oh weird... I'm able to see it normally on my system. Maybe try this link: 
[CHOWTapeModel-Win64-2.7.0.zip](https://github.com/jatinchowdhury18/AnalogTapeModel/files/5968556/CHOWTapeModel-Win64-2.7.0.zip)

**Comment by zainsohail04** [comment]
This works. I will let you know if I get GUI issue with this version. But since this only happened on two occasions, it might take time to show up.
