### ISSUE TITLE
[BUG] Application Can't Be Opened

### ISSUE THREAD

**Issue by jeremymeyers** [jatinchowdhury18/AnalogTapeModel#132]
Getting an error when attempting to open the standalone app on Mac Catalina 10.15.7
<img width="972" alt="Screen Shot 2021-02-16 at 6 10 44 PM" src="https://user-images.githubusercontent.com/3514095/108133349-69eaff80-7082-11eb-9194-61dc6fac68e3.png">

VSTs seem to work though.

**Comment by jatinchowdhury18** [comment]
Hi, thanks for reporting this!

Which version of ChowTape are you trying to run? Also, could you try the latest [development builds](https://github.com/jatinchowdhury18/AnalogTapeModel/blob/master/Plugin/Bin/CHOWTapeModel-Mac-2.7.0.zip). I ran the standalone version from that build on my computer today, and it worked fine.

Thanks,
Jatin
