### ISSUE TITLE
Tape Model produces unusual artefacts when processing chimes (mark tree) kind of material.

### ISSUE THREAD

**Issue by IsaakCode** [jatinchowdhury18/AnalogTapeModel#14]
(earlier report posted on KVR forum, here are some additional infos)

When using 'chimes' (mark tree) sounds the model produces strange artefacts in the low to lower mids spectrum (sounds similar to rumble / hum on a vinyl player).

Maybe some sort of unconventional aliasing is produced due to the amount of high frequency content and inharmonic overtones produced? [Wikipedia ](https://en.wikipedia.org/wiki/Mark_tree)states: "Unlike tubular bells, another form of chime, the chimes on a Mark tree do not produce a definite pitch, as they produce inharmonic (rather than harmonic) spectra."

When increasing the oversampling amount, the artefacts become less prominent, but are still very noticable even at 8x Oversampling in a 44100 Hz session. 

Decreasing the Input Gain won't do much in terms of reducing the artefacts (only reduction is due to the db decrease, but the amount of produced artefacts relative to the signal remains the same).

My guess is that chimes are a good sound source to determine how such a model reacts on very high frequency rich material, whether the performance of the model remains consistent?

Here are audio example (a) chimes sample without tape model and b) with tape model activated (change file ending from .txt to .wav)

[Chimes_WITHOUT_tape_model.txt](https://github.com/jatinchowdhury18/AnalogTapeModel/files/4118006/Chimes_WITHOUT_tape_model.txt)
[Chimes_with_tape_model.txt](https://github.com/jatinchowdhury18/AnalogTapeModel/files/4118007/Chimes_with_tape_model.txt)

My Setup: v2.0, VST3, Windows 64bit, Ableton Live 10.1, running at 44100 Hz sample rate 

P.S.

Please count me in if you ever need beta testers for your future plugins ;)

**Comment by jatinchowdhury18** [comment]
Hi Isaak,

Thanks for the bug report. My guess is that the artifacts we're hearing are caused by the extreme high frequency content of the signal, and that the only reason we don't hear it for more "normal" input is that the artifacts are masked by more low frequency sounds. This would also explain some why oversampling reduces the level of the artifacts.

I'll take a look at fixing the hysteresis function directly, but I should note that I've been playing around with some pre/post filters that most physical tape machines have, which may solve this issue indirectly anyway. (If you're curious, check out section 5 from [this manual](http://aes-media.org/historical/pdf/morrison_stl-manual.pdf)).

I'll update this thread with more info as I keep working on this. Thanks!

**Comment by jatinchowdhury18** [comment]
Hi Isaak,

After doing a bunch of testing and re-working a good bit of the math, I think this low frequency noise is going to be an inherent part of the hysteresis process, given the way I'm doing it currently. I've found that on normal input (with most of its frequency content below, say, 10k) the noise is not noticeable (though not to say that it's not there). I've found that for high frequency content like the chimes, putting a highpass filter on the track after the tape plugin can take care of most of the artifacts.

Unfortunately, the pre/post EQ doesn't seem to affect this issue either positively or negatively. Still hoping to have something new for you to test soon!

Thanks, as always :)

**Comment by IsaakCode** [comment]
Yes, I noticed that this issue only manifests in a rather obvious manner with those rare sounds that have their fundamental (or most of their lower order overtones) in the above 10k range. I didn't notice those artifacts with hihats for example and I don't use chimes too often anyways, so it's not really a big issue. 

Thank you and please keep up the good work Jatin! 

P.S.

I noticed on KVR earlier today you released builts of the "Bad Circuit Modelling" series. Great stuff again there! Tried the Diode Clipper so far and really like it (the only plugin I know that has age and temperature settings hihi). Could you add an output gain to compensate for the loudness increase?
