### ISSUE TITLE
JUCE 5.4.7 support

### ISSUE THREAD

**Issue by KottV** [jatinchowdhury18/AnalogTapeModel#16]
Hi!

With recent JUCE they changed:
AudioProcessorValueTreeState::getRawParameterValue now returns a
std::atomic<float>* instead of a float*.

So now AnalogTapeModel is unable to compile. I can change some paramteters to std::atomic<float>*
but have no idea what to do with this error:

> ../../Source/PluginProcessor.cpp:164:84: error: use of deleted function ‘std::atomic<_Tp>::atomic(const std::atomic<_Tp>&) [with _Tp = float]’
>   164 |     inGain.setGain  (Decibels::decibelsToGain (*vts.getRawParameterValue ("ingain")));
>       |     

                                                                               ^

**Comment by jatinchowdhury18** [comment]
Hi Konstantin!

Thanks for bringing this to my attention. I haven't looked too much at JUCE 5.4.7, and would prefer not to upgrade the whole project until I've had a better look. For now to get the project to compile you should be able to use the following code:
```c++
inGain.setGain  (Decibels::decibelsToGain (vts.getRawParameterValue ("ingain")->load()));
outGain.setGain (Decibels::decibelsToGain (vts.getRawParameterValue ("outgain")->load()));
```

For any other compiler errors, just changing `float*` to `std::atomic<float>*` should take care of them, as you described.

Definitely let me know if this works 👍!

Thanks,
Jatin

**Comment by KottV** [comment]
Yes it works. Thank You so much!
