### ISSUE TITLE
Degrade scales up very quickly

### ISSUE THREAD

**Issue by SomeoneCalledRob** [jatinchowdhury18/AnalogTapeModel#165]
The _Depth_ control of the Degrade section scales the effect up pretty quickly if the _Amount_ value is anything beyond a low number. Sometimes it's nice to have some barely detectable tape hiss on the master -- barely detectable even when wearing headphones. So my preference would be finer control over lower depth values, if possible.

**Comment by jatinchowdhury18** [comment]
That's a good point... It's important to be clever about how to implemen this though, since I'd rather not break existing settings that people have saved. I'm thinking the best option might be to have a multiplier parameter, that multiplies the *Depth* value by 0.1 or something like that. I'll give that a try and see how well it works.

**Comment by SomeoneCalledRob** [comment]
Thanks, that would probably work for me.

**Comment by jatinchowdhury18** [comment]
This feature has now been implemented, and can be tested in the [nightly builds](http://chowdsp.com/nightly.html). Big thanks to @NeelKanth333  for helping with the implementation!

**Comment by SomeoneCalledRob** [comment]
Just tested. It's much better and would even work as the default, with a button marked x10 to be engaged for more extreme settings. I've been trying it on a quiet, ambient-style track and even with the new 0.1x mode, I run it at low settings. But that's fine, as long as it works, which it does. Thanks again.

**Comment by jatinchowdhury18** [comment]
Great! Yeah, I tried it out in a couple mixes, and you're definitely right that the "just barely audible" hiss can be super useful. So thanks for the idea!

I think I'd prefer to keep the default behaviour as is, again just to avoid breaking saved settings that people currently have with the plugin. But I'll take some time to think about it and see if there's some way to compromise on that.
