### ISSUE TITLE
Massive pops and clicks

### ISSUE THREAD

**Issue by Flayzen** [jatinchowdhury18/AnalogTapeModel#17]
Using the VST2 version in FL Studio 20, Windows 10. This plugin will randomly emit pops and clicks that sends the meter into the red and keeps it there until disabled. Visualised in Voxengo SPAN the entire frequency spectrum is maxed out, then most of it fades leaving a permanent spike below 40hz.

**Comment by jatinchowdhury18** [comment]
Hi @Flayzen,

Thanks for trying it out! I haven't been able to recreate the bug on my system (I don't have FL unfortunately). Out of curiosity are you using a version downloaded from the `Bin/` folder, or compiled from source?

Thanks,
Jatin

**Comment by jatinchowdhury18** [comment]
Hi Flayzen,

I just uploaded a new release with a bunch of fixes. I've tested pretty extensively in Ableton, and it seems pretty robust to pops and clicks.  Any information as to how it works on your end would be great!

The new builds can be downloaded here: https://github.com/jatinchowdhury18/AnalogTapeModel/releases/tag/2.1

**Comment by Flayzen** [comment]
I'm using the CHOWTape-Win-2.1.0.zip file from https://github.com/jatinchowdhury18/AnalogTapeModel

I have just tried the new version and sadly it is still emitting occasional loud pops and clicks but this time it's not maxing out the meters.

**Comment by jatinchowdhury18** [comment]
Hi @Flayzen,

I've made some updates on this front! The updated Windows builds can be downloaded [here](https://github.com/jatinchowdhury18/AnalogTapeModel/tree/alpha-transform/Plugin/Bin). Please let me know if this is behaving better for you.

Thanks,
Jatin

**Comment by Sweet-del** [comment]
Hi

Really nice plugin. Thanks for this.

I have exactly the same Problems under FL20. Very loud pops and sometimes a audiodropout (sometimes both L+R, sometime only one L or R). When I bypass the plug a reactivate, then the audiodropout are gone.

**Comment by jatinchowdhury18** [comment]
Hi @Sweet-del,

Thanks for the report! Just to double check was this happening on the most recent release, or on the in-progress build posted in the comment above?

Thanks,
Jatin

**Comment by Sweet-del** [comment]
I took the .dll out of the folder under the marker "Code".

I made a record of the Pops an some Pictures in FL. I don't know if this helps to find the mistake. It seems as if the pop comes every "xx" seconds. After inserting the plug everything is finde. No Pops. But when the plug "gets Audio", then the Pops begins. And These Pops are getting louder. You can see it in die Pictures.

I made an Transfer via Dropbox
https://www.dropbox.com/t/fpfMoOPdUhVc676d

**Comment by jatinchowdhury18** [comment]
There's been somem updates on this front in the [latest release](https://github.com/jatinchowdhury18/AnalogTapeModel/releases/latest). Please let me know how the new version works for you!

**Comment by Sweet-del** [comment]
Hi @jatinchowdhury18 ,

Thanks for the update and the info. I tried the latest release and the Pops/clicks are still there. They are still getting louder and there is the same "time" between the clicks. I tried to locate the clicks and used every Parameter from Zero to full but the clicks are independent of parameter settings.

**Comment by jatinchowdhury18** [comment]
@Sweet-del Thanks for the updated info! I have a guess as to what the issue is, but if you could test something for me that would be very helpful. FL Studio has an option to "Use fixed size buffers" for a plugin. Would you be able to test the plugin with this setting and let me know how it works?

There's some more information on this issue at these links:
- https://forum.image-line.com/viewtopic.php?p=1334949
- https://www.kvraudio.com/forum/viewtopic.php?t=490542

**Comment by Sweet-del** [comment]
@jatinchowdhury18 

Wow. Thanks. I think you're on the right way. I tried both settings.

- **With** "use fixed Buffer size" and 
- **without** "use fixed Buffer size". 

In a small test (some minutes playing with audio) there are no more cracks by using "**use fixed Buffer size**. Thats fine. Thanks for the info.

I will try it in a big project.

Here are some pictures:

Without:

![without -use fixed buffer size-2](https://user-images.githubusercontent.com/65964596/83967213-c543db80-a8bf-11ea-8091-8bec9eaf5f79.jpg)

With:

![without -use fixed buffer size-](https://user-images.githubusercontent.com/65964596/83967215-ca088f80-a8bf-11ea-9fe2-92592dcb7609.jpg)

**Comment by Sweet-del** [comment]
@Flayzen 

Perhaps it work you too...try "used fixed size buffers" in the tab "detailed settings --> vst wrapper settings --> processing"

**Comment by Sweet-del** [comment]
Update:

I tested the function "used fixed size buffers" in a lot of big Projects with a lot of "Chow". And this fix does work perfectly. No more pops and clicks. Everything is fine now. 

@jatinchowdhury18 Thanks for support.

**Comment by chipmcdonald** [comment]
Is there a fix for Reaper?  I'm using 2.3 and have the same problem, random "snits" that triggers the auto-muting in Reaper.

Happens on playback, but seems to happen after altering something in an unrelated GUI on a different track, which is curious.

**Comment by jatinchowdhury18** [comment]
@chipmcdonald Still working on the Reaper bug. I have a couple clues, but I haven't fully got to the bottom of it, probably something related to the hysteresis stability. The relation to unrelated GUIs seems very strange, but DAWs do weird things sometimes, so who knows!
