### ISSUE TITLE
Clear up license

### ISSUE THREAD

**Issue by magnetophon** [jatinchowdhury18/AnalogTapeModel#185]
As part of packaging CHOWTapeModel for NixOS, I was [asked](https://github.com/NixOS/nixpkgs/pull/106746#discussion_r559766199) if the license is "GPL3 only" or "GPL3 or any later version".

I tried searching the code but didn't find my answer.

**Comment by jatinchowdhury18** [comment]
The intention was to be "GPLv3 or later". Is there a way to note this specifically in the License file?

**Comment by magnetophon** [comment]
AFAIK, most projects have the generic license, which mentions the option of "or any later version", and on top of that each/most source files have a short notice that specifies further.

Not sure why it's done in such a convoluted way though...
