### ISSUE TITLE
[BUG] Deb package has unnecessary -dev dependencies.

### ISSUE THREAD

**Issue by KottV** [jatinchowdhury18/AnalogTapeModel#193]
Hi!

**Describe the bug**
Deb package has -dev dependencies.

If you look into package:
```Depends: libasound2-dev, libcurl4-openssl-dev, libx11-dev, libxinerama-dev, libxext-dev, libfreetype6-dev, libwebkit2gtk-4.0-dev, libglu1-mesa-dev```
these packages may needed for build but not for binaries.

I haven't find build script for that. Perhaps these packages are listed in debian.control.

**Comment by jatinchowdhury18** [comment]
Thanks for mentioning this, I was actually just thinking about it the other day. Do you know if there's some kind of "sandboxed" environment, or something like that, that can be used to figure out what dependencies like this are needed at run-time?

By the way the "packaging" script for this plugin is located [here](https://github.com/Chowdhury-DSP/releases/blob/main/plugins/ChowTape/linux_build.sh).

**Comment by KottV** [comment]
>>By the way the "packaging" script for this plugin is located here.
got it, I'll take a look

I use Open Build Server for my builds. It can build Debian packages also,  I'll try to build your plugins in there. So it will have the proper dependencies.

**Comment by jatinchowdhury18** [comment]
Ah thanks for reminding me about Jack, I had accidentally disabled Jack when I switched to the CMake build system. I've re-enabled that now. I've also made a new build of the .deb that uses the dependencies that you had listed above, which can be downloaded [here](http://chowdsp.com/nightly.html). If this works out, then I can go ahead and adjust the Debian dependencies for all my other plugins in the build pipeline as well. Thanks for your help with this @KottV!

**Comment by KottV** [comment]
It works fine on Ubuntu 20.04, but I'm not sure that GH and OBS use exactly same Ubuntu. Is it possible to see /etc/os-release in your pipeline?

Also, I think that users may want Ubuntu 18 support too. I'll check how it builds there.

PS. Could you merge Jack support in master branch please? :)

**Comment by jatinchowdhury18** [comment]
> It works fine on Ubuntu 20.04, but I'm not sure that GH and OBS use exactly same Ubuntu. Is it possible to see /etc/os-release in your pipeline?

According to the [GitHub Actions Documentation](https://github.com/actions/virtual-environments), the build script is running on Ubuntu 20.04. I can see about adding a step to the pipeline as well to display the system info.

> Also, I think that users may want Ubuntu 18 support too. I'll check how it builds there.

Is there a reason that the .deb package built on 20.04 wouldn't work on Ubuntu 18? I had assumed backwards compatibility, but maybe that was a poor assumption on my part.

> PS. Could you merge Jack support in master branch please? :)

Done! :)

**Comment by KottV** [comment]
>According to the GitHub Actions Documentation, the build script is running on Ubuntu 20.04. I can see about adding a step to the pipeline as well to display the system info.

Good :)

>Is there a reason that the .deb package built on 20.04 wouldn't work on Ubuntu 18?

Yeah, it won't, main reason is the new glibc. But Ubuntu 18 builds should work on the newest versions.

>Done! :)

thnx!

**Comment by KottV** [comment]
JUCE wants cmake >3.12 while Ubuntu 18 has 3.10.2
I think it will be tricky to build here.

**Comment by jatinchowdhury18** [comment]
Oh yeah, that's a good point... is it difficult to update to update CMake on Ubuntu? I remember doing it with apt, but that was quite a while ago.

**Comment by KottV** [comment]
I read a bit, It's possible by:

1) Adding 3rd party repository: https://apt.kitware.com/
2) Building CMake manually.

First one won't work in OBS afaik may work in GitHub actions. Second should work everywhere, but means building/installing CMake prior in your scripts.

**Comment by jatinchowdhury18** [comment]
Yeah, now that you mention it I think I did end up building from source on my Ubuntu 18 system. For my CI and release pipelines, I use [this action](https://github.com/lukka/get-cmake), which seems to go pretty fast, so I doubt it is building from source. I wonder if it would be possible to reverse-engineer what they're doing, and do that in the scripts instead.

**Comment by KottV** [comment]
>I wonder if it would be possible to reverse-engineer what they're doing, and do that in the scripts instead.

https://github.com/lukka/get-cmake/blob/main/src/get-cmake.ts
Looks like it grabs binaries from https://github.com/Kitware/CMake/releases/download/v${ToolsGetter.CMakeVersion}/cmake-${ToolsGetter.CMakeVersion}-linux-x86_64.tar.gz`

for example ```${ToolsGetter.CMakeVersion} = 3.20.1```
https://github.com/Kitware/CMake/releases/download/v3.20.1/cmake-3.20.1-linux-x86_64.tar.gz

**Comment by jatinchowdhury18** [comment]
Ah okay, that seems pretty do-able... would I need to do that in my release scripts, or would that step be needed for building with OBS?

**Comment by KottV** [comment]
It need for GitHub release script.
Though it's kind of possible to put 3rd party binaries in OBS it is the really bad practice. I'm still thinking on workaround for OBS.

**Comment by jatinchowdhury18** [comment]
Gotcha that makes sense. I've now set my releases pipeline to use Ubuntu 18.04 instead of 20, so hopefully that should do the trick :).

**Comment by jatinchowdhury18** [comment]
Since I've had some confirmation that the Ubuntu-18.04 builds are working, and since the original purpose of this issue (-dev dependencies in the .deb package) is now resolved, I'm going to go ahead and close this issue.

**Comment by KottV** [comment]
Glad it worked!
