### ISSUE TITLE
[BUG] GUI non-responsive in FL Studio

### ISSUE THREAD

**Issue by SentryOverwatch** [jatinchowdhury18/AnalogTapeModel#194]
**Describe the bug**
When I Use the latest version (2.8.0) In fl studio, I'm unable to turn knobs or open menus. When I open it up by itself as standalone, it works fine.

**To Reproduce**
1. open up the plugin in fl
2. Click on any menu/knob.
3. it won't work.

**Expected behavior**
When I clicked, and held, my mouse on one of the knobs, and moved it, it should turn.
**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DAW: Fl Studio
 - Version: 2.8.0
 - both 32 and 64

**Additional context**
it worked fine before i updated it. If I use "external Window" mode it works fine.

**Comment by jatinchowdhury18** [comment]
Closing due to no response.
