### ISSUE TITLE
Feature request - offline oversampling settings

### ISSUE THREAD

**Issue by mstgrv** [jatinchowdhury18/AnalogTapeModel#198]
It'd be great to be able to set different oversampling settings for realtime & render, so that realtime playback can be at a lower setting and a much higher setting used for rendering.

**Comment by jatinchowdhury18** [comment]
Yeah, that's a neat idea! It shouldn't be too hard to do, although it relies on the DAW to tell the plugin that it's not running in real-time (leaving [this reference](https://docs.juce.com/master/classAudioProcessor.html#ac61949900870c9f6dca63d53ee68f7a0) for my future self).

From a UI perspective, do you have examples of other plugins that do something like this? I'm just trying to think of a way to implement it that doesn't seem clumsy, and doesn't clutter the menus along the bottom bar of the plugin.

**Comment by mstgrv** [comment]
There's a few devs who implement this sort of feature now, including for quality settings other than oversampling. A selection:

Cytomic (The Glue, The Drop) - you can get quite granular, and offline quality settings exceed those available for realtime:
<img width="340" alt="Screen Shot 2021-05-30 at 2 12 19 pm" src="https://user-images.githubusercontent.com/31542657/120091749-6111cb80-c151-11eb-943f-2146e98dc35a.png">

SIR StandardCLIP - offline settings also go higher than what's available for realtime:
<img width="856" alt="Screen Shot 2021-05-30 at 2 18 19 pm" src="https://user-images.githubusercontent.com/31542657/120091851-fd3bd280-c151-11eb-85a1-864902397b38.png">

Pulsar Mu - this update just came out, and the offline options are the same as available for realtime:
<img width="358" alt="Screen Shot 2021-05-30 at 2 12 35 pm" src="https://user-images.githubusercontent.com/31542657/120091773-87376b80-c151-11eb-8a1b-8db1e3c1a76f.png">

oeksound soothe2 - there's separate oversampling and resolution settings, including the ability to propagate the offline to other plugin instances in a project:
<img width="357" alt="Screen Shot 2021-05-30 at 2 13 00 pm" src="https://user-images.githubusercontent.com/31542657/120091796-a59d6700-c151-11eb-95b8-59a353e0feef.png">

Leapwing DynOne3 - just a plain setting for crossover quality when rendering (not very granular):
<img width="556" alt="Screen Shot 2021-05-30 at 2 14 19 pm" src="https://user-images.githubusercontent.com/31542657/120091814-c06fdb80-c151-11eb-88fd-290cc114add7.png">

**Comment by jatinchowdhury18** [comment]
@mstgrv thanks for the comprehensive list! There's a bunch of great ideas here, so I'm thinking to mix and match a few of them. Here's what I'm thinking to try first:

```
Oversampling menu:
|- Linear Phase
|- Minimum Phase
|--------------------
|- 1x
|- 2x
|- etc.
|--------------------
|- Offline
    |- Linear Phase
    |- Minimum Phase
    |--------------------
    |- 1x
    |- etc.
|- Current latency (x milliseconds)
```
Does that sound okay to you? Hopefully I can get started on it later this week! It might also be cool to have offline options for the Hysteresis Mode parameter, since that choice can have similar tradeoffs between CPU usage and sound quality.

**Comment by mstgrv** [comment]
I think that looks great! Something similar with hysteresis would be cool as well.

**Comment by jatinchowdhury18** [comment]
Just a head's up, there is now a (somewhat messy and thoroughly un-tested) implementation of this feature happening on [this branch](https://github.com/jatinchowdhury18/AnalogTapeModel/tree/oversampling-choices). Hoping to clean it up a bit tomorrow, and then merge not long after!

**Comment by jatinchowdhury18** [comment]
The latest [nightly builds](http://chowdsp.com/nightly.html) now have the updated oversampling menu, following the outline above. Let me know if you get a chance to try it out!

**Comment by not-holar** [comment]
Should such settings be per-instance or global? If the former, i think it would be good UX to make them always immediately visible (something like 1x/16x somewhere on the GUI), if the latter, they could be tucked away somewhere.

**Comment by not-holar** [comment]
![image](https://user-images.githubusercontent.com/58831297/121789397-4a05bb80-cbde-11eb-8d42-a69b52ccd4d3.png)
As an example, here's what per-instance oversampling looks like on The Glue's GUI.

**Comment by jatinchowdhury18** [comment]
@not-holar, yeah that's a good point. I'll see if I can adjust it so that it will show as **2x/8x** or something like that, unless "Same as real-time" is selected for the offline setting. Thanks for the idea!

**Comment by jatinchowdhury18** [comment]
<img width="166" alt="Screen Shot 2021-06-25 at 9 27 05 AM" src="https://user-images.githubusercontent.com/13724188/123456275-84386b00-d597-11eb-9f85-83e471afac2d.png">

The menu is now updated to show both the real-time and offline oversampling choices!
