### ISSUE TITLE
Compression addition

### ISSUE THREAD

**Issue by kirkmarkarian** [jatinchowdhury18/AnalogTapeModel#207]
While using this on EVERY mix I do - CHOWTapeModel is an amazing mastering plugin for providing a tape-sound - I am wondering if there is a way to create within the plugin a 'magnetic compression' sound on the peaks.  I am almost willing to bet that this exists already, and I'm just missing it.

I remember (and still experience) recording through various tape-recorders, when a transient it heavy, there's sometimes a degradation in the overall signal for just that specific moment.  Often described as a 'squish' or 'glue' sound when using audio compressors, but specific to tape recording, it provides a volume compression, but also a timbral change in sound.

**Comment by jatinchowdhury18** [comment]
That's definitely a good idea! There is a little bit of overlap between the "tape saturation" sound already present in the "Hysteresis" section of the plugin, I was reading the other day about an interesting algorithm for "ideal tape compression" that I think would be the right thing to add the extra "glue" that you mentioned. I'll do some research, and see if this is something that can be added here!

**Comment by jatinchowdhury18** [comment]
A tape compression processor has now been added and can be tested in the latest [nightly builds](http://chowdsp.com/nightly.html)

**Comment by kirkmarkarian** [comment]
It is EXCELLENT!!!  Adds just a little more of that tape-y 'oomph' to the sound.  Wonderful :)  THANK YOU!!!
