### ISSUE TITLE
[BUG] Please use github releases instead of placing binary assets in the git repo

### ISSUE THREAD

**Issue by falkTX** [jatinchowdhury18/AnalogTapeModel#209]
Well this is basically the same request as in https://github.com/jatinchowdhury18/KlonCentaur/issues/35
This repo needs the same treatment

> Receiving objects:  10% (882/8105), 184.17 MiB | 2.79 MiB/s

180Mb is only 10% :scream: 

this is going to take a long time....

EDIT: Final results:

> Receiving objects: 100% (8105/8105), 599.00 MiB | 2.83 MiB/s, done.

It is just shy of 600Mb

**Comment by jatinchowdhury18** [comment]
Ah, thanks for reminding me! Apologies, I haven't gotten around to fixing this for all my repos yet. Anyway, I just went through the cleanup process now, and the repo should be significantly smaller now.

Before cleanup:
```
$ git count-objects -vH
count: 0
size: 0 bytes
in-pack: 8105
packs: 1
size-pack: 599.22 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

After cleanup:
```
% git count-objects -vH
count: 0
size: 0 bytes
in-pack: 7348
packs: 1
size-pack: 116.83 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

**Comment by falkTX** [comment]
Yes a lot better now, thanks!
