### ISSUE TITLE
[BUG] Uninstaller for Windows copies itself to "Common Files" folder instead of its own location

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [jatinchowdhury18/AnalogTapeModel#219]
I think the installer should create directory like `C:\Program Files\ChowTapeModel`.

![image](https://user-images.githubusercontent.com/69355938/132924800-c6c54010-a24a-41bf-8cdf-6d583db8c138.png)

**Comment by jatinchowdhury18** [comment]
Thanks for reporting the issue! Unfortunately, I haven't been able to re-create the issue on my Windows machine. Could you please share the installer settings that you're using when this issue occurs? I.e. which components are you installing, and which paths are you installing too for each component? The last page of the installer should display this information.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Here's a screenshot:

![image](https://user-images.githubusercontent.com/69355938/133002369-b41583ac-88a0-4e11-9b6e-9baedfa165e8.png)

**Comment by jatinchowdhury18** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou would you be able to give this installer a try:

[ChowTapeModel-Win-2.9.0_ChangeDefDir.zip](https://github.com/jatinchowdhury18/AnalogTapeModel/files/7159198/ChowTapeModel-Win-2.9.0_ChangeDefDir.zip)

If the change I made was correct, it should be putting the uninstallers under `C:/Program Files/Chowdhury DSP/ChowTapeModel/...`

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Now after uninstalling and relaunching your archive with the same settings installation ends like this:

![image](https://user-images.githubusercontent.com/69355938/133286277-df608acb-30f4-498e-ae77-23d1776d42a4.png)

**Comment by jatinchowdhury18** [comment]
Wow that's strange, I don't get that error when running the same installer on my machine... I wonder what version of Windows you're running?

Also, here's another installer to try, that hopefulle has that error fixed:
[ChowTapeModel-Win-2.9.0_ChangeDefDir2.zip](https://github.com/jatinchowdhury18/AnalogTapeModel/files/7163830/ChowTapeModel-Win-2.9.0_ChangeDefDir2.zip)

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Nothing has changed. Maybe there is some strange bug in Inno Setup itself?

**Comment by jatinchowdhury18** [comment]
Hmm, could you give this one a try: [ChowTapeModel-Win-2.9.0_NoUn.zip](https://github.com/jatinchowdhury18/AnalogTapeModel/files/7190674/ChowTapeModel-Win-2.9.0_NoUn.zip)? I think it's just a question of getting the right mix of settings for Inno Setup. Thanks for bearing with me through this!

**Comment by jatinchowdhury18** [comment]
This fix had been validated by other testers, closing...
