### ISSUE TITLE
[FEATURE] Optional Mid-Side mode

### ISSUE THREAD

**Issue by not-holar** [jatinchowdhury18/AnalogTapeModel#222]
**Is your feature request related to a problem? Please describe.**
Mid-Side processing can give really interesting results and completely change how a plugin affects the sound. Right now, if you wanted to make chowTapeModel M-S, you'd have to use some other plugin before to encode MS into LR and then one after to decode it back, while it works, it's not very elegant.

**Describe the solution you'd like**
A simple toggle somewhere on the gui to switch between LR and MS processing could be a great way to switch things up.

**Comment by jatinchowdhury18** [comment]
Yeah, that's a cool idea! I think the trick will be figuring out where on the UI to put the switch...

I'm a bit busy with some life things at the moment, but hopefully I can get to this in a week or two!

**Comment by jatinchowdhury18** [comment]
This feature has now been implemented. Thanks to @NeelKanth333 for helping out with it!
