### ISSUE TITLE
New release with aarch64 build fix

### ISSUE THREAD

**Issue by Bleuzen** [jatinchowdhury18/AnalogTapeModel#243]
Hi, as you may remember there were arm build issues discussed in https://github.com/jatinchowdhury18/AnalogTapeModel/issues/236.
This is fixed now, but only on master branch.
However for flathub I usually only build from tags as this is what works with the update checker. Currently, while building from git master, the update checker is somewhat confused and suggests downgrades to the v2.10.0 tag.
A new fix release (2.10.1) would help with that.
Thanks :)

**Comment by jatinchowdhury18** [comment]
Hi! Yes, I can definitely see how that would be helpful for packaging. Unfortunately, whenever I tag a release on GitHub, everyone who uses the plugin will see a screen asking them if they would like to update to the latest release the next time they open it. For that reason, I try to avoid tagging releases, except when there are new features/big fixes that folks can enjoy when they install the new version.

I wonder if this issue could be avoided via the "meta" repository we were discussing... that way we can tag releases in that repo whenever any plugin is updated and it won't affect the individual plugin repos?

**Comment by Bleuzen** [comment]
Okay can see the problem here, didn't know the plugin has a built in update checker. In this case let's not annoy all the users with a new release which doesn't bring anything new to the table.

The meta repo could indeed solve it in this case so let's focus on that. I commented now on that corresponding issue.
Thanks a lot for working on this :)
