### ISSUE TITLE
[BUG] Labels do not scale with UI

### ISSUE THREAD

**Issue by hellocatfood** [jatinchowdhury18/AnalogTapeModel#259]
**Describe the bug**
When the plugin UI is rescaled the controls (knobs/faders) get lager but the text labels stay the same. This is particularly a problem when the UI is rescaled on HiDPI screens to make it more usable/legible.

**To Reproduce**
1. Grab the corner of the plugin window 
2. Resize to make it larger
3. See error (text labels stay the same size)

**Expected behavior**
Text should resize with the UI

**Screenshots**
Below is the plugin UI shown at its default size when opened in Carla on a HiDPI screen (3840x2400)

![Screenshot from 2022-04-26 22-24-11](https://user-images.githubusercontent.com/151947/165395819-3c6f8c14-ec11-4e06-8e7f-f5ca0943c212.png)

Below is the same plugin resized to fill most of the same screen.

![Screenshot from 2022-04-26 22-24-26](https://user-images.githubusercontent.com/151947/165396049-b3d92ad1-2607-4245-8459-4514fd88552f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - DAW: Carla
 - Version: 2.4.3

**Comment by jatinchowdhury18** [comment]
Thanks for reporting the issue! it definitely looks like we can do better when scaling up on higher resolution screens. There's a few things that I'm noticing from the screenshots, but please chime in if there's more things that you've noticed:
- top/bottom bar are too small
- "tabs" are too small
- rotary sliders are too large  and knob labels are too small
- linear sliders are too small
- some buttons (stereo, flutter sync) are too small
- tape speed buttons seem to be the correct size, but the text is too small

I also wonder if there's something about the way that Carla handles the window sizing and scale factor that could make this situation worse. Would it be possible to try running the plugin in "Standalone" mode to see if the scaling problem happens the same way?

I don't have a HiDPI monitor to test on at the moment, so I may need a little bit of help with testing, but I'll update this thread with any progress on the issue!

**Comment by hellocatfood** [comment]
What's the terminal command to run this plugin in standalone mode?

For reference I think this problem exists across all Chow plugins. I ran `ChowKick` and this is the size that it opened up at.

![Screenshot from 2022-04-27 10-15-38](https://user-images.githubusercontent.com/151947/165485562-7a469c4e-7c4d-4359-8802-c6cf27663452.png)

After resizing to fit the whole screen the labels don't resize

![Screenshot from 2022-04-27 10-15-51](https://user-images.githubusercontent.com/151947/165485792-68d1f973-7c54-44f8-8b30-bdc07f18892a.png)

**Comment by jatinchowdhury18** [comment]
The standalone plugin will be located in `build/CHOWTapeModel_artefacts/Release/Standalone/...` if you're building from source, or in `/usr/bin/...` if you're using the .deb installer. If you're installing from a different package, then I'm not totally sure where the standalone will be located.

I'm using the same UI framework for all our plugins, so I'm not surprised that the same issue shows up in multiple plugins. That said, hopefully if we fix the issue in one plugin, the same fix should translate pretty easily to the others as well!

**Comment by hellocatfood** [comment]
>  if you're building from source, or in /usr/bin/... if you're using the .deb installer.
I installed the deb from your website. What is the binary called? Running `ls | grep Chow` in `/usr/bin/` only brings up `ChowKick`

**Comment by jatinchowdhury18** [comment]
The name of the binary should be `CHOWTapeModel` (or `ChowKick` for the other plugin). I guess the capital letters might not be caught in the `grep` search? Although I suppose depending on how the debian package was installer, the binary could end up in `~/usr/bin/...` instead.

**Comment by hellocatfood** [comment]
Thanks for that. I was able to load the plugin and, as expected, the issue still exists.

**Comment by jatinchowdhury18** [comment]
Hi there! Sorry it's taken so long to get back to this. We've made some improvements in #281, and it would be great to know how things are looking on your screen with the latest [nightly build](https://chowdsp.com/nightly.html).

**Comment by hellocatfood** [comment]
all seems to be working now!
![Screenshot from 2022-07-10 18-44-43](https://user-images.githubusercontent.com/151947/178156093-05e0dc79-797e-45a6-a952-1cd6c6f0675e.png)
![Screenshot from 2022-07-10 18-45-02](https://user-images.githubusercontent.com/151947/178156094-bf7c830f-2396-481b-8e66-40cba3405ed2.png)
![Screenshot from 2022-07-10 18-45-15](https://user-images.githubusercontent.com/151947/178156096-84ef896c-6441-4d19-a0f0-b8d95c9e5226.png)

**Comment by jatinchowdhury18** [comment]
Awesome! Thanks again for reporting and testing.
