### ISSUE TITLE
[BUG] CLAP and VST3 do not have same latency compensation.

### ISSUE THREAD

**Issue by 38github** [jatinchowdhury18/AnalogTapeModel#289]
**Describe the bug**
AnalogTapeModel 2.11.0 does not have the same latency compensation between CLAP and VST3.

**To Reproduce**
1. Open a CLAP and a VST3 on separate channels and use same settings in both.
2. Phasey sound

**Expected behavior**
Same output from both plugins.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DAW: Reaper win64
 - Developer version
 - 64 bit (Windows only)

**Additional context**

**Comment by jatinchowdhury18** [comment]
Thanks for reporting this! I haven't actually tried running CLAP plugins in Reaper yet, but it was my understanding that Reaper's CLAP support was still a work-in-progress.

From testing in Bitwig, it seems like both the VST3 and CLAP plugins are reporting the same latency times (0.8 milliseconds in the plugin's default state, at 48 kHz sampling rate). This may be an issue to bring up to the Reaper developers.

**Comment by jatinchowdhury18** [comment]
Tested just now with Reaper version 6.71, and it looks like the issue has been resolved!
