### ISSUE TITLE
Spike on start playing

### ISSUE THREAD

**Issue by jatinchowdhury18** [jatinchowdhury18/AnalogTapeModel#29]
From KVR thread:

> This new build is causing a large volume spike for me (Reaper64, running on Linux/Wine 5.0) when starting playing, also at the start of a rendered track.

**Comment by eslepakurov** [comment]
The same issue - loud click when starting playing
Reaper, MacOS 10.14.6

**Comment by jatinchowdhury18** [comment]
Sorry it's taken me so long to get to this. This should be fixed with #57. I'll have some builds available soon to test this fix.

**Comment by eslepakurov** [comment]
It's ok. Good luck with your work.
Nice job.

**Comment by jatinchowdhury18** [comment]
New builds are available for testing here: https://github.com/jatinchowdhury18/AnalogTapeModel/blob/develop/Plugin/Bin/MacBuilds.zip

Definitely let me know if this behavior is still occurring on your machine.
