### ISSUE TITLE
[FEATURE] Build command excluding CLAP on building instructions

### ISSUE THREAD

**Issue by lee-yunseok** [jatinchowdhury18/AnalogTapeModel#295]
**Is your feature request related to a problem? Please describe.**

RPi users **cannot build** AnalogTapeModel because of `cmake_minimum_required`

`CMake Error at modules/clap-juce-extensions/CMakeLists.txt:13 (cmake_minimum_required):
  CMake 3.21 or higher is required.  You are running version 3.18.4`

This problem is caused by the build CLAP.

**Describe the solution you'd like**

Add command to turn off the build CLAP like BYOD.

**Comment by jatinchowdhury18** [comment]
Ah good call! I made a commit to the `develop` branch just now using the same CMake strategy. Let me know if it works out for you!

**Comment by lee-yunseok** [comment]
Yes it works :)
