### ISSUE TITLE
Freeze Loop[BUG]

### ISSUE THREAD

**Issue by Skinsplasher** [jatinchowdhury18/AnalogTapeModel#297]
**Describe the bug**
Freezes then unfreezes for a second, then freezes again (looped ad infinitum)

**To Reproduce**
1. Go to main interface
2. Click on presets (possibly other things but havent been able to test)
3. scrolling not possible
4. enters a freeze loop state
5. 
**Expected behavior**
no freeze loop?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - DAW Cakewalk
 - cakewalk 2022.11 (build 021), chowtape 2.11
 - 64 bit 

**Additional context**
tried to recreate with my other juce plugs, and also chowtape regular vst instead of vst3

**Comment by jatinchowdhury18** [comment]
Thanks for reporting the issue! I pushed a fix that should address this issue the other day. If you get a chance would you mind trying out the latest [nightly build](https://chowdsp.com/nightly.html#tape), and make sure that the OpenGL setting is switched "ON" (see the settings menu in the bottom right corner of the plugin).

**Comment by Skinsplasher** [comment]
Yessss. worked like a charm. I can't test extensively atm, but the initial issue was solved. Thanks for quick reply. I was so bummed, because I want to use the hell out of this. You did some great work on it
