### ISSUE TITLE
[BUG] Rendering freezes in Cubase

### ISSUE THREAD

**Issue by Sparirata1** [jatinchowdhury18/AnalogTapeModel#298]
**Describe the bug**
Hello! Love the plugin but i've been having this issue with it for the past months: Every time I open it in Cubase it freezes Cubase and the plugin, if I Ctrl+Alt_Delete then the plugin unfreezes until I click Cubase, which then freezes them both again. after a bit the Ctrl+Alt Delte trick stops helping and i am forced to shut down Cubase and reopen it. When the plugin is inside the project but CHOWTAPEMODEL window isn't open then it works fine. I've tried uninstalling and reinstalling multiple time but it doesn't help. opening the standalone app on my desktop works fine.

I really am fan of your plugins, and this one in particular is my favorite of yours, I've refrained from using it since this bug showed up but I'm working on a project that desperately need its sound, hope you can help, thank you and have a great day!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DAW Cubase 10 Pro
 - Chow Version V2.11.0
 -64 bit (Windows only)

**Comment by jatinchowdhury18** [comment]
Hi, thanks for reporting the issue! We've actually been working on improving compatibility for graphics rendering with several hosts on Windows, so if you're able to try out the latest [nightly build](https://chowdsp.com/nightly.html), that would be very helpful.

Another useful thing would be to try both settings for the "Enable OpenGL" option in the plugin settings menu.

**Comment by Sparirata1** [comment]
Thanks! Ill give it a shot and post here how it goes ;0

**Comment by Sparirata1** [comment]
Using OpenGL did the trick! Thank you so much I can finally use this plugin again XD

**Comment by jatinchowdhury18** [comment]
Okay great!
