### ISSUE TITLE
Separate Wow/Flutter controls

### ISSUE THREAD

**Issue by jatinchowdhury18** [jatinchowdhury18/AnalogTapeModel#33]
From @Boscop,

>  I think it would make sense to have a second set of 2 knobs for wow ("depth" and "rate" just like for flutter).
I'm not an expert on tape, but AFAIK both wow and flutter can occur at the same time (flutter being fast and wow being slow), right?

**Comment by jatinchowdhury18** [comment]
I think this could be neat. The current "flutter" processor uses a delay line modulated by 3 oscillators, that have been fit to the shape of the flutter/wow that I measured from my own tape machine. I can play around with separating these, e.g, the lowest oscillator could be "wow", and the higher two could be "flutter".

Hopefully this could make it into the next release (maybe 1.5-2 weeks out).

**Comment by Boscop** [comment]
Thanks :)
Btw, as for the GUI, you could put those 2 knobs in a new tab (like the tabs it already has for Loss, Degradation, Chew). 
So on the right side there would be two tabs: "Wow" and "Flutter".
