### ISSUE TITLE
Knob movement not smooth [BUG]

### ISSUE THREAD

**Issue by djdarkstep** [jatinchowdhury18/AnalogTapeModel#50]
Since 2.3.3 the knob movement stopped being buttery and became jittery and not smooth overall.

**Comment by jatinchowdhury18** [comment]
Hi @djdarkstep, thanks for the bug report! Could you also let me know which OS and DAW you're using? (If on Windows, 32-bit vs. 64-bit is also helpful). Thanks!

**Comment by djdarkstep** [comment]
Hi! I'm on Windows 10 x64 and REAPER v6.12 x64, using the VST3 version.
By the way, the plugin sounds phenomenal, thank you!

**Comment by jatinchowdhury18** [comment]
Hi @djdarkstep, I did some work on this bug. Let me know how the builds in [this folder](https://github.com/jatinchowdhury18/AnalogTapeModel/tree/Sliders-bug/Plugin/Bin/Win64) work for you.

**Comment by djdarkstep** [comment]
Yes! The knobs are smooth again. Thank you!
