### ISSUE TITLE
Plugin GUI shows incorrect version number

### ISSUE THREAD

**Issue by mstgrv** [jatinchowdhury18/AnalogTapeModel#55]
Just downloaded 2.3.4 for Mac, and all plugin formats show "2.3.0" on the GUI. Would be great if the GUI reflected the actual plugin version.

**Comment by jatinchowdhury18** [comment]
Ah, thanks for reporting this! I've updated the release with the correct builds: https://github.com/jatinchowdhury18/AnalogTapeModel/releases/tag/v2.3.4
