### ISSUE TITLE
[BUG] Broken link to Catalina download

### ISSUE THREAD

**Issue by breun** [jatinchowdhury18/AnalogTapeModel#76]
**Describe the bug**
https://github.com/jatinchowdhury18/AnalogTapeModel#installation says:

> If you need a build that is compatible with Mac OS Catalina, try [this link](https://www.dropbox.com/s/n14b1ju8kofp71v/CHOWTape.zip).

When I click that link Dropbox shows me a 404 Not Found screen.

**To Reproduce**
1. Go to https://github.com/jatinchowdhury18/AnalogTapeModel#installation
2. Click on '[this link](https://www.dropbox.com/s/n14b1ju8kofp71v/CHOWTape.zip)'
3. See 404 error screen

**Expected behavior**
I expected to be able to download a build that is compatible with macOS Catalina.

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Comment by jatinchowdhury18** [comment]
Ah, thanks for reporting this. I'll see if I can get in touch with the person who had uploaded the Catalina build, seems like they've deleted the file or removed the link. In the meantime, I'll edit the README so as not to mislead users.

Thanks,
Jatin
