### ISSUE TITLE
CPU spikes (

### ISSUE THREAD

**Issue by IsaakCode** [jatinchowdhury18/AnalogTapeModel#8]
Running the plugin (VST3 version, Windows 7 64bit, Ableton Live 10.1) causes extreme CPU spikes. Abletons CPU meter shows between 90% and 125% CPU taxation. This might be partially due to constantly activated 16x oversampling that can not be switched off or reduced currently and probably due to unoptimized algorithm.

**Comment by jatinchowdhury18** [comment]
Hi Isaak,

Thanks for the note. After a bunch of updates (see #9), this is now running at about 12% CPU on my machine (VST2, Windows 10 64-bit, Ableton 10.1), with 8x oversampling. I've also included options for 2x, or 4x oversampling, which give even better CPU performance. Planning to have new build uploaded later today!
